inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
AllCops:
  TargetRubyVersion: 3.0.6
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false