inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'config/environments/**'
    - 'spec/**/**'
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Naming/MemoizedInstanceVariableName: 
  Enabled: true
  Exclude:
    - 'app/controllers/**'

Metrics/AbcSize:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  Exclude:
    - 'spec/**/**'
    - app/services/posts/create.rb
    - app/controllers/**
    - app/services/posts/creation.rb

Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - 'app/controllers/posts_controller.rb'
    - 'app/jobs/unseen_comments_notification_job.rb'
    - 'app/services/posts/show.rb'

Style/GuardClause:
  Enabled: true
  Exclude:
    - 'app/controllers/posts_controller.rb'
