Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'app/controllers/post_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/post_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'app/models/user.rb'
    - 'config/application.rb'
    - 'db/migrate/20230918113548_devise_create_users.rb'

  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'
