name: Checks code

on:
  push:
  pull_request:

jobs:
  rubocop:

    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.0.6']
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checks code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run rubocop
      run: bundle exec rubocop