name: RSpec Test

on:
  - push
  - pull_request

jobs:
  test:

    strategy:
      fails-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: 
          - '3.0.6'
    runs-os: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4.1.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.155.0

      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run test
      run: bundle exec rspec .