default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["POSTGRES_USER"].presence || "default" %>
  password: <%= ENV["POSTGRES_PASSWORD"].presence || "default" %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: postapp_dev
  pool: 10

test:
  <<: *default
  database: postapp_test
  pool: 10

production:
  <<: *default
  database: postapp_prod