default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: volodymyr
  password: '654321'
  host: localhost
  port: 5432

development:
  <<: *default
  database: Postapp_dev

test:
  <<: *default
  database: Postapp_test
  host: localhost

production:
  <<: *default
  database: Postapp_prod