default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch("POSTGRES_USER") { "default" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "default" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>

development:
  <<: *default
  database: postapp_dev

test:
  <<: *default
  database: postapp_test

production:
  <<: *default
  database: postapp_prod