name: Cop

on:
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Checks code
      uses: actions/checkout@v4.1.0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.6'
        bundler-cache: true
      - run: echo $PATH | tr ':' '\n'
      - run: bundle info rubocop
      - run: gem which rubocop
      - name: Run rubocop
        run: rubocop --parallel