name: RuboCop

on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Check code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.6

    - name: Install gem
      run: gem install rubocop

    - name: Run RuboCop
      run: bundle exec rubocop