name: Checks code

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Checks code
      uses: actions/checkout@v4.1.0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.6'
        bundler-cache: true

    - name: Run rubocop
      run: bundle exec rubocop