name: RSpec

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] 
        ruby: 
          - '3.0.6'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4.1.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

      run: bundle exec rspec