name: RSpec Tests

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: 
          - '3.2.2'
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: default
          POSTGRES_PASSWORD: default
          POSTGRES_DB: postapp_test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          
      - name: Setup and Migrate Database
        run: |
          bundle exec rake db:setup
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASWORD: ${{ secrets.POSTGRES_PASWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }} 

      - name: Run RSpec Tests
        run: bundle exec rspec