name: RSpec Tests

on: [push]

jobs:
  test:
    
runs-on: ubuntu-latest

    steps:
    - name: Check code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.6

    - name: Install Bundler 
      run: gem install bundler

    - name: Install gem
      run: bundle install

    - name: Run RSpec Tests
      run: bundle exec rspec