name: RSpec Tests

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: 
          - '3.2.2'
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: volodymyr
          POSTGRES_PASSWORD: 654321

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup and Migrate Database
        run: |
          bundle install
          bundle exec rake db:setup RAILS_ENV=test
      - name: Run RSpec Tests
        run: bundle exec rspec