name: RSpec Test

on:
  push:
  pull_request:

jobs:
  test:
  runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.6'
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec