name: RSpec Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: volodymyr
          POSTGRES_PASSWORD: 654321
          POSTGRES_DB: Postapp_test
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v2
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Setup and Migrate Database
        run: bundle exec rake db:setup RAILS_ENV=test

      - name: Run RSpec Tests
        run: bundle exec rspec