name: RSpec Test

on:
  push:
  pull_request:

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: [3.0.6]
      fail-fast: false

    runs-version: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec